version: "3.9"

services:
  backend:
    container_name: curamyn-backend
    image: nazina/curamyn-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      CURAMYN_ENV: prod
      CURAMYN_MONGO_URI: ${CURAMYN_MONGO_URI}
      CURAMYN_MONGO_DB: ${CURAMYN_MONGO_DB}
      CURAMYN_GEMINI_API_KEY: ${CURAMYN_GEMINI_API_KEY}
    restart: unless-stopped

  frontend:
    container_name: curamyn-frontend
    image: nazina/curamyn-frontend:latest
    ports:
      - "8080:8080"
    environment:
      CURAMYN_API_BASE_URL: http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
