version: "3.9"

services:
  backend:
    container_name: curamyn-backend
    image: curamyn-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Core
      CURAMYN_ENV: prod
    

      # Database
      CURAMYN_MONGO_URI: ${CURAMYN_MONGO_URI}
      CURAMYN_MONGO_DB: ${CURAMYN_MONGO_DB}

      # LLM
      CURAMYN_GEMINI_API_KEY: ${CURAMYN_GEMINI_API_KEY}

    restart: unless-stopped

  frontend:
    container_name: curamyn-frontend
    image: curamyn-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    environment:
      # IMPORTANT: use service name, NOT localhost
      CURAMYN_API_BASE_URL: http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

